import * as Router from 'koa-router'
import { createSNSTopic, createSQSQueue, getSQSArn, subscribeSQStoSNS, updateSQSPermissions } from './aws/create'
import { publish } from './aws/publish'

// variables generated by creating sns topics & sqs queues
interface ConfigInterface {
  snsTopicArn?: string
  sqsQueueUrl?: string
  sqsQueueArn?: string
}
let config: ConfigInterface = {}

const router: Router = new Router()

router.get('/', ctx => {
  ctx.body = 'Hi there'
})

router.get('/create', async ctx => {
  const sqsQueueUrl = await createSQSQueue('demo')
  if(!sqsQueueUrl) throw new Error('SQS Queue Url is not available')

  const sqsQueueArn = await getSQSArn(sqsQueueUrl)
  const snsTopicArn = await createSNSTopic('demo')
  if(!(snsTopicArn && sqsQueueArn)) throw new Error('ARN is missing in SNS or SQS')

  await subscribeSQStoSNS(snsTopicArn, sqsQueueArn)
  await updateSQSPermissions(snsTopicArn, sqsQueueUrl, sqsQueueArn)

  // make Arn available
  config.sqsQueueUrl = sqsQueueUrl
  config.sqsQueueArn = sqsQueueArn
  config.snsTopicArn = snsTopicArn

  ctx.body = {
    message: 'Setup is fine'
  }
})

router.get('/publish', async ctx => {
  const publishData = await publish(config.snsTopicArn)

  ctx.body = {
    MessageId: publishData.MessageId
  }
})

export { router }